### ISSUE TITLE
Some servers doesn't works

### ISSUE THREAD

**Issue by ketamina96** [xPaw/PHP-Source-Query-Class#46]
Hi. I saw some servers refuse to work via this script. I checked all details and all are good , but this script just don't wanna read them :)) Query is enabled and servers aren't localhost. What could be wrong ?

**Comment by HaibaneNero** [comment]
Can you provide the names of the server or add more information how to reproduce the problem?

**Comment by ketamina96** [comment]
Server's IP is 89.46.223.190 and Port: 27015. It's a public server, no password. The script is just loading a while then show an empty template...

**Comment by HaibaneNero** [comment]
Im using `PHP 5.4.39-0+deb7u2` and it seems to work fine. Have you changed anything since opening this issue? What PHP Version do you use?

**Comment by ketamina96** [comment]
5.2 .. and i never changed smth ..

**Comment by Kubo2** [comment]
Does the script output any kind of errors? (If not, do you have display_errors On? If not, turn it on and try again.) If it doesn't output anything, I could take some time to debug it (on PHP 5.2.x).

**Comment by ketamina96** [comment]
There's no errors... I need special PHP modules ?

**Comment by Kubo2** [comment]
@ketamina96: Which 5.2 do you use? Because there are various bugfixes between PHP 5.2.10 and 5.2.17.

**Comment by Kubo2** [comment]
@ketamina96:

I have just ~~tested~~ tried to test your issue on PHP 5.2.17 and it can't work at all. When loading files we use magic constant `__DIR__` which is not yet defined in PHP 5.2, so it would fail like `Fatal error: require() failed opening required...`.

<hr>

Okay, I just ran:

`C:/php-5.2.17/php.exe -l SourceQuery.class.php`

and the output is following:

```
Parse error: syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in SourceQuery.class.php on line 23
Errors parsing SourceQuery.class.php
```

This is because there is no namespaces support yet in PHP 5.2. So we should probably mention this __minimal requirement of PHP version >= 5.4__ somewhere in README to avoid similar issues in future.

/cc @xPaw

**Comment by xPaw** [comment]
Namespaces and __DIR__ were added in 5.3, not 5.4.

**Comment by Kubo2** [comment]
Sorry for that, I were never using PHP 5.3, so it was only assumption due to `__DIR__` -- people in manual comments at php.net were saying that there is some bug with this in 5.3.

**Comment by xPaw** [comment]
5.3 is end of life anyway, I've put a note about using 5.4.
